# Generated by Django 5.1.1 on 2024-09-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_calllog_delete_caller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='caller_number',
            new_name='CallFrom',
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='call_status',
            new_name='DialCallDuration',
        ),
    ]
