# Generated by Django 5.1.1 on 2024-09-18 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_rename_caller_number_calllog_callfrom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='calllog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
