# Generated by Django 5.1.1 on 2024-09-18 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_remove_calllog_created_at_calllog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
