# Generated by Django 5.1.1 on 2024-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_data',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('tokenNo', models.IntegerField(primary_key=True, serialize=False)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('diseaseInfo', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
