# Generated by Django 5.1.1 on 2024-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_data',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form_data',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
