# Generated by Django 5.1.1 on 2024-09-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_forms', '0002_form_data_phone_alter_form_data_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_data',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='form_data',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
