# Generated by Django 5.1.1 on 2024-09-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_forms', '0003_remove_form_data_birthdate_form_data_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
